version: '2.2'

services:
  delos:
    container_name: rap2-delos
    image: taomaree/rap2:1.0.4
    environment:
      - MYSQL_URL=rap2-mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=rap2
      - MYSQL_PASSWD=rap2delos
      - MYSQL_SCHEMA=RAP2_DELOS_APP
      - REDIS_URL=rap2-redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    working_dir: /app/rap2-delos/dist
    volumes:
      - "/srv/rap2-mysql/mysql-backup:/backup"
    ports:
      - "38080:80"  # expose 38080
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql


  redis:
    container_name: rap2-redis
    image: redis:4.0.9


  mysql:
    container_name: rap2-mysql
    image: mysql:8.0.12
    #ports:
    #   - 33306:3306
    volumes:
      - "/srv/rap2-mysql/mysql-data:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --default-authentication-plugin=mysql_native_password --innodb-flush-log-at-trx-commit=0 
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=RAP2_DELOS_APP
      - MYSQL_USER=rap2
      - MYSQL_PASSWORD=rap2delos

  rap2-init:
    container_name: rap2-init
    image: taomaree/rap2:1.0.4
    environment:
      - MYSQL_URL=rap2-mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=rap2
      - MYSQL_PASSWD=rap2delos
      - MYSQL_SCHEMA=RAP2_DELOS_APP
      - REDIS_URL=rap2-redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    working_dir: /app/rap2-delos
    #command: 'mysql -h${MYSQL_URL} -u${MYSQL_USERNAME} -p${MYSQL_PASSWD} -e "select * from ${MYSQL_SCHEMA}.Users;" || npm run create-db'
    command: ["bash", "-c", "sleep 30 && mysql -h$${MYSQL_URL} -u$${MYSQL_USERNAME} -p$${MYSQL_PASSWD} -e \"select * from $${MYSQL_SCHEMA}.Users;\" || node dist/scripts/init"]
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql
